app/src/main/res/layout/collection_item.xml, app/src/main/res/values-sw600dp/dimens.xml, app/src/main/res/values-sw720dp/dimens.xml, app/src/main/res/values/dimens.xml
=> Make library images smaller

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/dev/jdtech/jellyfin/database/ServerDatabaseDao.kt, app/src/main/java/dev/jdtech/jellyfin/di/ApiModule.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/AddServerFragment.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/LoginFragment.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/MediaFragment.kt, app/src/main/java/dev/jdtech/jellyfin/tv/ui/TvAddServerFragment.kt, app/src/main/java/dev/jdtech/jellyfin/tv/ui/TvLoginFragment.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/AddServerViewModel.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/LoginViewModel.kt, app/src/main/res/layout/fragment_add_server.xml, app/src/main/res/layout/fragment_login.xml, app/src/main/res/values/strings.xml
General server setup improvements:
- New UI State system
- Make UI adapt to keyboard
- Improve connection and login logic
- Keyboard go action
=> Server setup improvements

app/src/main/AndroidManifest.xml, app/src/main/java/dev/jdtech/jellyfin/PlayerActivity.kt, app/src/main/java/dev/jdtech/jellyfin/utils/AppPreferences.kt, app/src/main/java/dev/jdtech/jellyfin/utils/Constants.kt, app/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt, app/src/main/java/dev/jdtech/jellyfin/utils/extensions.kt, app/src/main/res/layout/exo_player_view.xml
- No more false brightness and volume trigger on status bar swipe [ Exoplayer , MPV]
- Remember last brightness set [ Exoplayer , MPV]
- Pinch to zoom and auto rotate Player [ Exoplayer ]
=> Player improvement

README.md, app/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt
Playlist support for MPV player
=> Playlist support for MPV player.

app/src/main/java/dev/jdtech/jellyfin/utils/DownloadUtilities.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/fragment_settings.xml
Added a switch in settings to enable the change.
=> Add switch to toggle downloads over mobile network

app/build.gradle.kts, app/src/main/java/dev/jdtech/jellyfin/viewmodels/EpisodeBottomSheetViewModel.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/MediaInfoViewModel.kt
minSdk 24 -> 26
targetSdk 31 -> 32
compileSdk 31 -> 32
=> Target SDK 32, up minimum to 26

app/src/main/res/values/string_arrays.xml, app/src/main/res/values/strings.xml
Weblate cannot translate string-arrays
=> Move string-arrays to different file

app/src/main/res/values-b+es+419/strings.xml, app/src/main/res/values-es-rMX/strings.xml, app/src/main/res/values-es/strings.xml
Refactored to match with default string file, minor fiexs and new strings translated.
=> Update new strings for spanish

app/src/main/java/dev/jdtech/jellyfin/dialogs/TrackSelectionDialogFragment.kt, app/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt
add an empty track with ffIndex = -1 to disable subtitles when it is selected
=> Disable subtitle in mpv

app/build.gradle.kts, app/src/main/java/dev/jdtech/jellyfin/adapters/ViewItemPagingAdapter.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/LibraryFragment.kt, app/src/main/java/dev/jdtech/jellyfin/repository/ItemsPagingSource.kt, app/src/main/java/dev/jdtech/jellyfin/repository/JellyfinRepository.kt, app/src/main/java/dev/jdtech/jellyfin/repository/JellyfinRepositoryImpl.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/LibraryViewModel.kt
This should improve performance a lot when dealing with large libraries.
Loads 10 items at a time with a maximum of 100 items in the recyclerview.
Closes #64
=> Add paging support to LibraryFragment

app/src/main/java/dev/jdtech/jellyfin/fragments/SettingsCacheFragment.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/SettingsPlayerFragment.kt, app/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt, app/src/main/java/dev/jdtech/jellyfin/utils/AppPreferences.kt, app/src/main/java/dev/jdtech/jellyfin/utils/Constants.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/fragment_settings_player.xml
Adds the ability to customize the seeking increments.
The options are located in the player settings.
Defaults:
- back: 5000 ms
- forward: 15000 ms
=> Customize the seeking increments

app/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt, app/src/main/res/layout/activity_player.xml
Allow seeking video by swiping or tapping.
=> Allow seeking video by swiping or tapping

app/src/main/java/dev/jdtech/jellyfin/BindingAdapters.kt, app/src/main/java/dev/jdtech/jellyfin/adapters/UserListAdapter.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/LoginFragment.kt, app/src/main/java/dev/jdtech/jellyfin/models/User.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/LoginViewModel.kt, app/src/main/res/drawable-television/user_placeholder.xml, app/src/main/res/drawable/ic_user_color_on_primary.xml, app/src/main/res/drawable/user_placeholder.xml, app/src/main/res/layout-television/fragment_login.xml, app/src/main/res/layout-television/user_item.xml, app/src/main/res/layout/fragment_login.xml, app/src/main/res/layout/home_episode_item.xml, app/src/main/res/layout/user_item.xml
Display public users on the login fragment
- Auto-fill username when pressed
- Show user name and image
=> Display public users on login fragment

app/src/main/AndroidManifest.xml, app/src/main/java/dev/jdtech/jellyfin/adapters/DiscoveredServerListAdapter.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/AddServerFragment.kt, app/src/main/java/dev/jdtech/jellyfin/models/DiscoveredServer.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/AddServerViewModel.kt, app/src/main/res/layout-television/discovered_server_item.xml, app/src/main/res/layout-television/fragment_add_server.xml, app/src/main/res/layout/discovered_server_item.xml, app/src/main/res/layout/fragment_add_server.xml
Display discovered servers on AddServerFragment
- Displays server name and an icon
- Connects to the selected server when pressed
=> Discover servers

app/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt, app/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt
=> Fix "pinch to zoom" for MPV

app/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt
This was broken because the subfont.ttf was never loaded.
By setting "config" to "yes" it now loads the font.
=> Fix mpv SubRip Text (SRT) not rendering

app/proguard-rules.pro, app/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerViewModel.kt, app/src/main/res/values/strings.xml
This add external subtitles support to mpv.
This also includes an updated libmpv version.
=> Fix mpv external subtitles

app/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt
Closes #162
Some .ass subtitles will still be broken due to their forced stylings unless stripped.
=> Fix MPV subtitles zoom in

app/src/main/java/dev/jdtech/jellyfin/fragments/EpisodeBottomSheetFragment.kt, app/src/main/res/layout/episode_bottom_sheet.xml, app/src/main/res/navigation/app_navigation.xml
- Add series name to the episode sheet
- Navigate to the series when clicked
- Also limit the episode name to 3 lines
Closes #171
=> Add series name to episode sheet with navigation

app/src/main/java/dev/jdtech/jellyfin/MainActivity.kt, app/src/main/java/dev/jdtech/jellyfin/adapters/UserLoginListAdapter.kt, app/src/main/java/dev/jdtech/jellyfin/database/ServerDatabaseDao.kt, app/src/main/java/dev/jdtech/jellyfin/di/ApiModule.kt, app/src/main/java/dev/jdtech/jellyfin/dialogs/DeleteUserDialogFragment.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/LoginFragment.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/SettingsFragment.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/UsersFragment.kt, app/src/main/java/dev/jdtech/jellyfin/models/Server.kt, app/src/main/java/dev/jdtech/jellyfin/utils/AppPreferences.kt, app/src/main/java/dev/jdtech/jellyfin/utils/Constants.kt, app/src/main/java/dev/jdtech/jellyfin/utils/extensions.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/AddServerViewModel.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/LoginViewModel.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/UsersViewModel.kt, app/src/main/res/drawable/ic_plus.xml, app/src/main/res/layout/fragment_users.xml, app/src/main/res/layout/user_list_item.xml, app/src/main/res/navigation/app_navigation.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/fragment_settings.xml
Add the ability have multiple users per server.
Switching between users requires you to login again. (This is required because the Jellyfin server invalidates all other access token on a device when logging in)
This implementation is still pretty rough but should allow to more easily switch between users.
=> Multi-user support

app/src/main/java/dev/jdtech/jellyfin/MainActivity.kt, app/src/main/java/dev/jdtech/jellyfin/adapters/ServerAddressAdapter.kt, app/src/main/java/dev/jdtech/jellyfin/database/ServerDatabaseDao.kt, app/src/main/java/dev/jdtech/jellyfin/dialogs/AddServerAddressDialog.kt, app/src/main/java/dev/jdtech/jellyfin/dialogs/DeleteServerAddressDialog.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/ServerAddressesFragment.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/SettingsFragment.kt, app/src/main/java/dev/jdtech/jellyfin/fragments/UsersFragment.kt, app/src/main/java/dev/jdtech/jellyfin/models/Server.kt, app/src/main/java/dev/jdtech/jellyfin/viewmodels/ServerAddressesViewModel.kt, app/src/main/res/drawable/ic_globe.xml, app/src/main/res/layout-television/fragment_server_addresses.xml, app/src/main/res/layout/fragment_server_addresses.xml, app/src/main/res/layout/fragment_users.xml, app/src/main/res/layout/server_address_list_item.xml, app/src/main/res/navigation/app_navigation.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/fragment_settings.xml
Adds support for having multiple addresses per server.
This can be useful for people who want to add their server via a public and private ip for external and internal use respectively.
=> Multiple server addresses

app/src/main/java/dev/jdtech/jellyfin/fragments/HomeFragment.kt, app/src/main/res/menu/home_menu.xml, app/src/main/res/navigation/app_navigation.xml
Add a search button on the home screen so users don't have to go to the media screen every time they want to search something
Closes #84
=> Add search button on home screen

app/build.gradle.kts, app/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt, app/src/main/res/values/string_arrays.xml, build.gradle.kts, gradle/libs.versions.toml
Remove the prebuilt libmpv and use the one from the maven repo.
The source code for libmpv is available [here](https://github.com/jarnedemeulemeester/libmpv-android)
=> Use libmpv from maven repository

app/phone/src/main/java/dev/jdtech/jellyfin/fragments/LoginFragment.kt, app/phone/src/main/res/layout/fragment_login.xml, core/src/main/java/dev/jdtech/jellyfin/viewmodels/LoginViewModel.kt, core/src/main/res/values/strings.xml, data/src/main/java/dev/jdtech/jellyfin/api/JellyfinApi.kt
Add Quick Connection functionality to the login screen.
Closes #226
=> Log in with Quick Connect

app/phone/src/main/java/dev/jdtech/jellyfin/PlayerActivity.kt, app/phone/src/main/res/layout/exo_player_view.xml, build.gradle.kts, core/src/main/res/values/strings.xml, core/src/main/res/xml/fragment_settings_player.xml, data/build.gradle.kts, data/proguard-rules.pro, data/src/main/java/dev/jdtech/jellyfin/models/Intro.kt, data/src/main/java/dev/jdtech/jellyfin/repository/JellyfinRepository.kt, data/src/main/java/dev/jdtech/jellyfin/repository/JellyfinRepositoryImpl.kt, gradle/libs.versions.toml, player/video/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt, preferences/src/main/java/dev/jdtech/jellyfin/AppPreferences.kt, preferences/src/main/java/dev/jdtech/jellyfin/Constants.kt
Closes #163 and half of #146
Sorry for the awful code, I'm not an android app developer so you should probably take this PR only as a suggestion,
but it works fine for me
=> Add intro skipper support

app/phone/src/main/java/dev/jdtech/jellyfin/fragments/CollectionFragment.kt, app/phone/src/main/java/dev/jdtech/jellyfin/fragments/LibraryFragment.kt, app/phone/src/main/res/navigation/app_navigation.xml, core/src/main/java/dev/jdtech/jellyfin/models/CollectionType.kt, core/src/main/java/dev/jdtech/jellyfin/viewmodels/CollectionViewModel.kt, core/src/main/java/dev/jdtech/jellyfin/viewmodels/LibraryViewModel.kt
Add support for collections.
Uses the same layout as the FavoriteFragment. 
A better layout may be implemented when we switch to compose.
Closes #18
=> Implement collections

gradle/libs.versions.toml, player/video/build.gradle.kts
Adds the androidx.media3.exoplayer-hls library / extension
Closes #206
=> Enable HLS playback in ExoPlayer

app/phone/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt, core/src/main/res/values/strings.xml, core/src/main/res/xml/fragment_settings_player.xml, preferences/src/main/java/dev/jdtech/jellyfin/AppPreferences.kt, preferences/src/main/java/dev/jdtech/jellyfin/Constants.kt
Add option in the setting to disable the seek gesture.
Also refactor `PlayerGestureHelper` a bit to make it easier to maintain.
Close #265
=> feat(settings): add option to toggle seek gesture

core/src/main/res/values-zh-rCN/strings.xml
Currently translated at 100.0% (166 of 166 strings)
Translation: Findroid/core
Translate-URL: https://weblate.jdtech.dev/projects/findroid/core/zh_Hans/
=> chore(translate): (Chinese (Simplified))

renovate.json
I think this will look better in the pull request tab. If you want to merge this, make sure to first create the label dependencies since it doesn't exist yet in this repo.
=> Add label dependencies to Renovate Bot PRs

core/src/main/res/values-night/themes.xml, data/src/main/java/dev/jdtech/jellyfin/repository/JellyfinRepositoryOfflineImpl.kt
Closes https://github.com/jarnedemeulemeester/findroid/issues/361
=> fix: amoled theme not taking M3 colors

app/phone/src/main/java/dev/jdtech/jellyfin/fragments/MovieFragment.kt, app/phone/src/main/res/layout/item_info.xml, core/src/main/java/dev/jdtech/jellyfin/utils/DownloaderImpl.kt, core/src/main/res/values-b+es+419/strings.xml, core/src/main/res/values-es/strings.xml, core/src/main/res/values-pl/strings.xml, core/src/main/res/values-pt-rBR/strings.xml, core/src/main/res/values-ru/strings.xml, core/src/main/res/values-sk/strings.xml, core/src/main/res/values/strings.xml
=> feat: show movie size in extra info and improve size formatting

build.gradle.kts, data/build.gradle.kts, gradle/libs.versions.toml
Migrate `androidx.room` from kapt to ksp
=> refactor: migrate room from kapt to ksp

app/phone/build.gradle.kts, app/phone/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt, core/build.gradle.kts, data/build.gradle.kts, player/core/build.gradle.kts, player/video/build.gradle.kts, preferences/build.gradle.kts
Target SDK 34 (Android 14) :tada: 
Requires one fix in `PlayerGestureHelper`.
Everything else seems to work fine.
=> feat: target sdk 34

app/phone/src/main/java/dev/jdtech/jellyfin/fragments/EpisodeBottomSheetFragment.kt, app/phone/src/main/res/layout/episode_bottom_sheet.xml
=> feat: show episode size in extra info

README.md
=> Add Discord group badge in README

app/phone/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt, core/src/main/res/values/strings.xml, core/src/main/res/xml/fragment_settings_player.xml, preferences/src/main/java/dev/jdtech/jellyfin/AppPreferences.kt, preferences/src/main/java/dev/jdtech/jellyfin/Constants.kt
Adding a setting for starting player as maximized by default
- Resolves #569
=> feat: start player maximized pref

app/phone/src/main/java/dev/jdtech/jellyfin/PlayerActivity.kt, app/phone/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt
Sorry, I found one more problem.
=> fix: pip zoom start player maximized

README.md
Now that chapters are merged
- #466
=> Add chapter feature to README

app/phone/src/main/java/dev/jdtech/jellyfin/fragments/LoginFragment.kt, app/phone/src/main/res/layout/fragment_login.xml, app/tv/src/main/java/dev/jdtech/jellyfin/ui/LoginScreen.kt, core/src/main/java/dev/jdtech/jellyfin/viewmodels/LoginViewModel.kt
When entering user login credentials the login disclaimer from the server admin will be shown:
=> feat: add login disclaimer support

app/tv/src/main/java/dev/jdtech/jellyfin/ui/AddServerScreen.kt, app/tv/src/main/java/dev/jdtech/jellyfin/ui/LoginScreen.kt
Tested on:
- Virtual TV (with virtual TV remote)
- Actual TV (with TV remote)
=> feat(tv): handle keyboard action for IME Action Go

fastlane/metadata/android/de/short_description.txt
Found this in our local tree, but missing here – so sending it up in the hope you find it useful 😉 It's just the German short description, though…
=> add de locale to fastlane
