jarnedemeulemeester/findroid

app/src/debug/res/drawable/ic_download_filled.xml
app/src/main/AndroidManifest.xml
app/src/main/java/dev/jdtech/jellyfin/MainActivity.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/EpisodeBottomSheetFragment.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/MediaInfoFragment.kt
app/src/main/java/dev/jdtech/jellyfin/models/DownloadMetadata.kt
app/src/main/java/dev/jdtech/jellyfin/utils/DownloadUtilities.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/DownloadViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/EpisodeBottomSheetViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/HomeViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/MediaInfoViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerViewModel.kt
app/src/main/res/values/strings.xml

This pull request adds the following improvements to the offline playback feature:
- Fix a bug in download playback tracking
- Remove the unused external storage permission
- Add the overview text to downloaded metadata
- Add a visual indicator of whether an item is downloaded or not
- Use the downloaded item if it is available instead of streaming it from the server

Improve offline playback

---

app/src/main/java/dev/jdtech/jellyfin/PlayerActivity.kt

I added the option to turn off the subtitles for a video which has subtitles enabled by default. Turns out you just have to enable the `ShowDisableOption` in the `TrackSelectionDialogBuilder`.
This fixes #82.
Here is a screenshot of the new option ("Ohne" = None, my phone is set to German).

Add option to turn off subtitles

---

app/proguard-rules.pro
app/src/main/java/dev/jdtech/jellyfin/PlayerActivity.kt
app/src/main/java/dev/jdtech/jellyfin/di/GlideModule.kt
app/src/main/java/dev/jdtech/jellyfin/utils/AppPreferences.kt
app/src/main/java/dev/jdtech/jellyfin/utils/Constants.kt
app/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt
app/src/main/res/values-b+es+419/strings.xml
app/src/main/res/values-cs-rCZ/strings.xml
app/src/main/res/values-es-rMX/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/fragment_settings_cache.xml
app/src/main/res/xml/fragment_settings_player.xml

Provide some more configurable options.
These include:
- Player gestures (true)
- Remember player brightness level (false)
Changes these defaults:
- Cache images: false -> true
- Cache size: 250 -> 20
Also includes a fix for ProGuard removing the SettingsFragments

Extra settings

---

app/src/main/java/dev/jdtech/jellyfin/BindingAdapters.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/AddServerFragment.kt

When the user added a server using a trailing slash `/` ex. `demo.jellyfin.org/stable/` all images fail to load.
A simple fix is to remove all trailing slashes when adding the server.
The only issue with this is that the users who added their server with a trailing slash will have to first remove and then add their server again.
An other solution could be to remove trailing slashes every time an image request is made, but this would not be ideal for performance.
Fix #113

Fix trailing slash in baseUrl not loading images

---

app/src/main/java/dev/jdtech/jellyfin/utils/AppPreferences.kt
app/src/main/java/dev/jdtech/jellyfin/utils/Constants.kt
app/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt
app/src/main/res/values-b+es+419/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es-rMX/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/fragment_settings_player.xml

Adds two more options to individually disable the following gestures:
- Volume and brightness
- Zoom
Before you could only disable all player gestures.
Closes #120

Split gesture option into volume & brightness and zoom

---

app/build.gradle.kts
app/src/main/java/dev/jdtech/jellyfin/BindingAdapters.kt
app/src/main/java/dev/jdtech/jellyfin/adapters/HomeEpisodeListAdapter.kt
app/src/main/java/dev/jdtech/jellyfin/adapters/ViewItemListAdapter.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/DownloadFragment.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/FavoriteFragment.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/HomeFragment.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/LibraryFragment.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/MediaInfoFragment.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/PersonDetailFragment.kt
app/src/main/java/dev/jdtech/jellyfin/fragments/SearchResultFragment.kt
app/src/main/java/dev/jdtech/jellyfin/models/ContentType.kt
app/src/main/java/dev/jdtech/jellyfin/models/DownloadItem.kt
app/src/main/java/dev/jdtech/jellyfin/repository/JellyfinRepository.kt
app/src/main/java/dev/jdtech/jellyfin/repository/JellyfinRepositoryImpl.kt
app/src/main/java/dev/jdtech/jellyfin/tv/ui/HomeFragment.kt
app/src/main/java/dev/jdtech/jellyfin/tv/ui/MediaSectionPresenter.kt
app/src/main/java/dev/jdtech/jellyfin/utils/DownloadUtilities.kt
app/src/main/java/dev/jdtech/jellyfin/utils/extensions.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/DownloadViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/FavoriteViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/LibraryViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/MediaInfoViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/PersonDetailViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/SearchResultViewModel.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/SettingsDeviceViewModel.kt
app/src/main/res/navigation/app_navigation.xml
app/src/main/res/navigation/tv_navigation.xml

The main change is using BaseItemKind to specify the item type.
This drops support for 10.7.x.
The minimum version of the Jellyfin server is now 10.8.0.

Upgrade to jellyfin-sdk 1.3.0

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/network_security_config.xml

A patch from jellyfin/jellyfin-android#179 to make self-signed or user added CAs work.

Add Network security config to trust user added CA

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/dev/jdtech/jellyfin/BaseApplication.kt
app/src/main/java/dev/jdtech/jellyfin/MainActivity.kt
app/src/main/java/dev/jdtech/jellyfin/utils/AppPreferences.kt
app/src/main/java/dev/jdtech/jellyfin/utils/Constants.kt
app/src/main/res/values-night/themes.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/themes.xml
app/src/main/res/xml/fragment_settings_appearance.xml

Enable Material You dynamic colors on all activities.
This also removes the `androidx.core.core-splashscreen` library because of an incompatibility between the splash screen and the dynamic colors.
A poll on Discord has decided that the dynamic colors are more important than the splash screen.
Note: Android 12+ has a built-in splash screen for all apps. Only Android <12 uses the splash screen library.
Closes #133

Enable Material You Dynamic colors

---

app/src/main/java/dev/jdtech/jellyfin/fragments/SettingsPlayerFragment.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/fragment_settings_player.xml

Add a subtitles button in the settings which navigates to the Android system caption settings.
This is where the appearance of the subtitles can be changed.
Closes #151

Add subtitles settings button to player settings

---

app/src/main/java/dev/jdtech/jellyfin/MainActivity.kt
app/src/main/java/dev/jdtech/jellyfin/viewmodels/MainViewModel.kt

When loading the app on TV for the first time the startDestination is not changed to the addServerFragment.
This fixes that.
Fix #159

[TV] Set correct navigation start destination

---

app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

Use a version catalog to centralize all project dependencies and versions.
This will make it easy for a bot like renovate to upgrade the dependencies.
And also helps when we start splitting this project into modules.

Use version catalog

---

app/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt

Handle the audio focus, so that findroid cooperates with other media players.
For example, findroid will now pause when the user gets a call.

Handle audio focus

---

app/src/main/res/layout-w600dp-television/activity_main.xml

The activity_main.xml at "app/src/main/res/layout-w600dp-television/activity_main.xml" was a symlink to "app/src/main/res/layout-television/activity_main.xml" causing the build to fail. To resolve this, copied the activity_main.xml from layout-television to layout-w600db-television.

[fix] activity_main was a symlink, converted to xml file

---

data/src/main/java/dev/jdtech/jellyfin/repository/JellyfinRepositoryImpl.kt

The `getIntroTimestamps` function would throw an error if any error other than a 404 occured. This isn't a problem when playing from the server, because it must be available to stream the video at all. However, when playing from downloads, the server doesn't need to be available, and the function throws an error. I fixed this by making the function never throw an error.

Fix downloads when intro skipper is enabled and server is not reachable

---

player/video/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt

With this pr, users don't have to click the play button when playing from downloads in mpv. This is achieved by adding a 1ms delay just before the `player.prepare()` function is called. For some reason, this ensures it doesn't crash when that function is called, so we can now call it, fixing having to manually press play.

Fix mpv in downloads

---

player/video/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt

When exiting the player when the file has ended the player would crash if using mpv player.
This was due to a pretty stupid mistake in the eof check in MpvPlayer
This also makes sure the player closes when it finishes playing the last item.

Fix mpv player crashing on exiting the player when the item has finished playing

---

data/src/main/java/dev/jdtech/jellyfin/repository/JellyfinRepositoryImpl.kt

Turns out that the exception thrown when internet is completely disabled isn't an `InvalidStatusException`, so I just made it catch every exception. Fixes #261

Fix downloads with introskipper enabled (again)

---

core/src/main/res/layout/preference_material3_switch.xml
core/src/main/res/values/themes.xml
core/src/main/res/xml/fragment_settings_appearance.xml
core/src/main/res/xml/fragment_settings_cache.xml
core/src/main/res/xml/fragment_settings_downloads.xml
core/src/main/res/xml/fragment_settings_player.xml

Since the app is built around Material3, we can use overlays as of now for `androidx.preferences`. Also, the `ListPreference` looks much cleaner and modern for selections with Material3.

feat(ui): make preference dialogs and switches material3-esque

---

player/video/src/main/java/dev/jdtech/jellyfin/mpv/MPVPlayer.kt
player/video/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt

- Fix the stuck loading icon when using mpv
- Remove observers when quitting
- Replace deprecated audio focus methods
- Fix ANR when leaving player
Fix #271

fix(mpv): memory leak, stuck loading icon, anr, deprecated methods

---

core/src/main/res/values/styles.xml
core/src/main/res/values/themes.xml
core/src/main/res/xml/fragment_settings_appearance.xml
core/src/main/res/xml/fragment_settings_cache.xml
core/src/main/res/xml/fragment_settings_downloads.xml
core/src/main/res/xml/fragment_settings_player.xml

Optimising #268 even more, we can define a custom style for the preference so that we don't have to add `widgetLayout` everytime!

refactor(ui): use a global preference style for Material3 switch

---

core/src/main/res/values/strings.xml

Redundant periods have been removed to standardise translation.

Update strings.xml for translation needs

---

app/phone/src/main/java/dev/jdtech/jellyfin/fragments/LibraryFragment.kt
core/src/main/java/dev/jdtech/jellyfin/viewmodels/LibraryViewModel.kt

Remember scroll position in `LibraryFragment` by using caching and only loading the pager once.
Fix: #201

fix: remember scroll position in `LibraryFragment`

---

app/phone/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt
preferences/src/main/java/dev/jdtech/jellyfin/Constants.kt

- Previously, the use of system gestures (such as the back and home gestures) resulted in the invocation of app gestures (such as seek, volume and brightness gestures), causing conflicts with the system gestures.
- This PR solves the issue of conflicting gestures by adding mandatory system gesture insets. These insets represent the areas of the window where system gestures have priority. This implementation is in line with the guidelines provided by the Android Developers website. And also this closes #281

fix: Implementation of Mandatory System Gesture Insets to Avoid Conflicts with System Gestures

---

.github/workflows/build.yaml

Split the build job into lint and assemble.
This way we still have APK artifacts even when the linting fails.

ci: split build job into lint and assemble

---

app/phone/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt

Previously, when swiping up to increase the volume to its maximum level and keeps swiping up causes the volume tracker value to increase as much as we swipe, swiping down afterwards would not adjust the volume until the volume tracker value reached the maximum volume value. This issue has been resolved so that volume adjustment occurs immediately after swiping down.

fix: volume gesture tracker value does not stay within bounds

---

core/src/main/java/dev/jdtech/jellyfin/dialogs/DeleteServerAddressDialog.kt

Not tested. Saw it while using the app and it looked like an easy fix.

fix: spelling error in remove address dialog

---

app/phone/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt

This patch enhances the `onDoubleTap` method within the media player component. It introduces a split-screen layout where the player view is divided into three equal areas (in the ratio of 2:1:2).
1. Leftmost Area: When double-tapped, it seeks the media playback backward by the defined seek increment
(`appPreferences.playerSeekBackIncrement`).
2. Middle Area: A double-tap in this area toggles the play/pause state of the player. If the player is currently playing, it will be paused, and if it's paused, it will be resumed.
3. Rightmost Area: When double-tapped, it seeks the media playback forward by the specified seek increment
(`appPreferences.playerSeekForwardIncrement`).

feat: Add seek and play/pause functionality to onDoubleTap

---

app/phone/build.gradle.kts
app/phone/src/main/java/dev/jdtech/jellyfin/BasePlayerActivity.kt
core/build.gradle.kts
data/build.gradle.kts
player/core/build.gradle.kts
player/video/build.gradle.kts
preferences/build.gradle.kts

Up the minimum SDK to 28 (Android 9).
Of all installs on Google Play less then 1% is on Android 8.1, so I think we can drop this version.
This also allows us to remove some Android 9 specific checks.
However this change does increase the generated APK's file sizes. This is because starting with minSdk 28 the dex files are uncompressed by default. See https://developer.android.com/reference/tools/gradle-api/8.1/com/android/build/api/dsl/DexPackaging?hl=en#useLegacyPackaging()
This does not affect APK's generated from AAB like what the Google Play Store does.
For now I will not enable `useLegacyPackaging`, but if APK size becomes a problem then this could be enabled.

build: up min sdk to 28

---

core/src/main/java/dev/jdtech/jellyfin/work/SyncWorker.kt

Fixes #464 by using `OnPlaybackStopped` instead lf `OnPlaybackProgress` for syncing.

Fix playback sync issue

---

app/phone/src/main/res/layout/base_item.xml
core/src/main/res/drawable/bg_rounded_rect_12dp.xml

Fixes #445
The episode indicator background was constrained to a 24dp box. If this box could not contain the count, then the count would wrap onto a new line.
The proposed solution is to use a rounded rectangle as the background instead. This can then expand into a chip as needed to accommodate larger numbers without wrapping.
See below how this looks like with 1, 2, and 4 digits:

fix episode indicator wrapping on second line

---

app/phone/src/main/java/dev/jdtech/jellyfin/fragments/DownloadsFragment.kt

This affected also all tablets since they use the landscape view!
Added `setTextMaxLines` because for some reason the text is truncated on tablets.
- Fixes #470.
Thanks @Jcuhfehl for the help :D

fix: snackbar not showing in landscape mode

---

app/phone/src/main/java/dev/jdtech/jellyfin/MainActivity.kt
preferences/src/main/java/dev/jdtech/jellyfin/AppPreferences.kt

Pretty sure enough time has passed since this was introduced and we can remove it :)

refactor: remove `cleanUpOldDownloads`

---

app/phone/build.gradle.kts
app/tv/build.gradle.kts
core/build.gradle.kts
data/build.gradle.kts
player/core/build.gradle.kts
player/video/build.gradle.kts
settings.gradle.kts

Use type-safe project accessors ([introduced in Gradle 7](https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors))

chore: use type-safe project accessors

---

app/phone/src/main/java/dev/jdtech/jellyfin/PlayerActivity.kt
app/phone/src/main/java/dev/jdtech/jellyfin/utils/PlayerGestureHelper.kt

- When you exit PiP mode "Fit to screen" state doesn't reset. 
Closes #519 
- When you enter PiP mode disable BRIGHTNESS_OVERRIDE.
Closes Discord issue
Maybe add a setting to enable/disable this option? Let me know

fix: pip remember Zoom and auto-brightness

---

app/phone/src/main/java/dev/jdtech/jellyfin/PlayerActivity.kt
player/video/src/main/java/dev/jdtech/jellyfin/viewmodels/PlayerActivityViewModel.kt

Make transitions to PiP mode smoother from gesture navigation: 
https://github.com/jarnedemeulemeester/findroid/assets/65548905/152a7a31-9d71-4bd9-97cf-a5e9b8ca9f91
> Demo from: https://developer.android.com/develop/ui/views/picture-in-picture
For Android 12 and newer, only tested on android 14.

feat: automatic PiP animation

---

core/src/main/res/values-w600dp/dimens.xml
core/src/main/res/values-w720dp/dimens.xml
core/src/main/res/values-w840dp/dimens.xml

The library span count is too small on pad when screen is portrait, so reduce w600dp and w720dp span count, and add w840dp span count.
See: https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes

fix: library media item too small on pad when screen is portrait

---

app/phone/src/main/java/dev/jdtech/jellyfin/adapters/EpisodeListAdapter.kt
app/phone/src/main/java/dev/jdtech/jellyfin/fragments/EpisodeBottomSheetFragment.kt
app/phone/src/main/java/dev/jdtech/jellyfin/fragments/MovieFragment.kt
app/phone/src/main/java/dev/jdtech/jellyfin/fragments/ShowFragment.kt

feat: support html in media description

---

settings/src/main/res/drawable/ic_closed_caption.xml
settings/src/main/res/drawable/ic_download.xml
settings/src/main/res/drawable/ic_hard_drive.xml
settings/src/main/res/drawable/ic_info.xml
settings/src/main/res/drawable/ic_languages.xml
settings/src/main/res/drawable/ic_network.xml
settings/src/main/res/drawable/ic_palette.xml
settings/src/main/res/drawable/ic_play.xml
settings/src/main/res/drawable/ic_server.xml
settings/src/main/res/drawable/ic_server_off.xml
settings/src/main/res/drawable/ic_speaker.xml
settings/src/main/res/drawable/ic_user.xml

The colorControlNormal attribute could not be resolved and was causing build failures when selecting "Compile all sources" in Android Studio or "gradlew build" from the command line.  The colorControlNormal attribute is resolved in the Android theme, but the settings submodule did not have any theme, so it could not be resolved.
The tint is applied by Jetpack Compose Icon, so it's not needed in the drawable XML anymore.
Note: You could remove all of the settings drawables and replace them with ImageVectors.  However I found it to be difficult to map all of the current drawables to the Material Icons (you may need the extended icons).  If this is desirable, you may need to compromise with a different icon that has the same meaning.

settings compile errors: remove tint from drawables
